### ISSUE TITLE
My honest reaction

### ISSUE THREAD

**Issue by sefinek24** [Viamonte4652/Genshin-Stella-Mod-for-RUcomm#1]
My honest reaction VV

https://github.com/Viamonte4652/Genshin-Stella-Mod-for-RUcomm/assets/92880265/51ec247b-3ff2-4e45-923b-7edaca3b4c55

![6b61878bacebe2733534fad536a70f76fbd7f39f_full](https://github.com/Viamonte4652/Genshin-Stella-Mod-for-RUcomm/assets/92880265/c1efec55-4ed6-4781-83ea-41bcccf7daad)

**Comment by Viamonte4652** [comment]
🤡❤ 
https://www.youtube.com/watch?v=dRRt-U2QPAg&t=210s&ab_channel=PARODYHUB

**Comment by sefinek24** [comment]
I just expressed my position.
As for the joke, yes, but if I remember correctly, the 'anti-Russian cunt system' was commented out in the code by me some time ago. I won't give you the specific commit because I don't write the names of specific commits. Currently, Stella Mod does not throw a bluescreen, it only shows a Russian cunt. (I brought it back again after some time, hehe)
![IMG_20220810_133130-1-1](https://github.com/Viamonte4652/Genshin-Stella-Mod-for-RUcomm/assets/92880265/c2f7f571-478b-4297-9dc5-1a9f43c088f9)

**Comment by Viamonte4652** [comment]
![image](https://github.com/Viamonte4652/Genshin-Stella-Mod-for-RUcomm/assets/86967093/6395243c-17c9-4dd3-9079-657d344ae8e9)
Nice mod launcher you made, I agree with that.
But you don't let us use it, and that's sad.
Of course, if you didn't, I'd buy the plus version, but apparently that's not in your best interest, and yes, the sanctions haven't blocked any payment method, so it's possible to do it, but for the sake of a joke I don't see the point.

**Comment by sefinek24** [comment]
What you see was added in 2022, I believe. In 2023, in the `Program.cs` file, I commented out the line that launches the form with the Russian cunt

Do you want to know why I disgrace the Russian nation? Mainly because of idiots in CS2

**Comment by Viamonte4652** [comment]
> What you see was added in 2022, I believe. In 2023, in the `Program.cs` file, I commented out the line that launches the form with the Russian cunt
> 
> Do you want to know why I disgrace the Russian nation? Mainly because of idiots in CS2


I agree, CS2 in Russia is played by fucking 12-18 year old school kids obsessed with cheats and other shit, so even I don't even download it🤣.

**Comment by Viamonte4652** [comment]
One more piece of advice, don't join Dota2 with Russians, they're all fuckers there.
That's the most inadequate players you've ever seen in your life.
